table olist_order_payments_dataset
	lineageTag: 7432f21a-1fa7-4ccb-be4e-c6b91d139d6d

	column order_id
		dataType: string
		lineageTag: a58795f3-7b10-4fc0-a781-be830906550c
		summarizeBy: none
		sourceColumn: order_id

		annotation SummarizationSetBy = Automatic

	column payment_sequential
		dataType: int64
		formatString: 0
		lineageTag: 90d5aa21-30e7-4cf3-9e5a-ededdd03ce7d
		summarizeBy: sum
		sourceColumn: payment_sequential

		annotation SummarizationSetBy = Automatic

	column payment_type
		dataType: string
		lineageTag: 5c8ee193-cdc6-41da-acac-58bf36508e7f
		summarizeBy: none
		sourceColumn: payment_type

		annotation SummarizationSetBy = Automatic

	column payment_installments
		dataType: int64
		formatString: 0
		lineageTag: 43b0f37f-8ee1-4ff6-bcb9-40ebc025a2ee
		summarizeBy: sum
		sourceColumn: payment_installments

		annotation SummarizationSetBy = Automatic

	column payment_value
		dataType: double
		formatString: 0
		lineageTag: 726ebeee-eb4e-48b9-814e-0e971031c448
		summarizeBy: sum
		sourceColumn: payment_value

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isDecimal":true}

	partition olist_order_payments_dataset = m
		mode: import
		source =
				let
				    Fonte = Csv.Document(File.Contents("C:\Users\Nitro V15\Desktop\PowerBI Projects\datasets\olist_order_payments_dataset.csv"),[Delimiter=",", Columns=5, Encoding=1252, QuoteStyle=QuoteStyle.None]),
				    #"Cabeçalhos Promovidos" = Table.PromoteHeaders(Fonte, [PromoteAllScalars=true]),
				    #"Tipo Alterado" = Table.TransformColumnTypes(#"Cabeçalhos Promovidos",{{"order_id", type text}, {"payment_sequential", Int64.Type}, {"payment_type", type text}, {"payment_installments", Int64.Type}, {"payment_value", Int64.Type}}),
				    #"Tipo Alterado1" = Table.TransformColumnTypes(#"Tipo Alterado",{{"payment_value", type number}})
				in
				    #"Tipo Alterado1"

	annotation PBI_NavigationStepName = Navegação

	annotation PBI_ResultType = Table

